name: PrismAnchorExample
version: '${version}'
main: org.cupelt.example.prismanchor.example.PrismAnchorExample
api-version: '1.20'

commands:
  test:
    description: Your description
    usage: /<command>